version: '3.8'

services:
  postservice_db:
    image: mysql:8.0
    container_name: postservice_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: postservice_db
    ports:
      - "3306:3306"

  commentservice_db:
    image: mysql:8.0
    container_name: commentservice_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: commentservice_db
    ports:
      - "3307:3307"

  reviewservice_db:
    image: mysql:8.0
    container_name: postservice_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: postservice_db
    ports:
      - "3308:3308"