server:
  port: 8083

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
              - "http://127.0.0.1:4200"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
              - "PATCH"
            allowedHeaders:
              - "Content-Type"
              - "Authorization"
              - "Origin"
              - "Accept"
              - "X-Requested-With"
              - "Access-Control-Request-Method"
              - "Access-Control-Request-Headers"
              - "User"
              - "Role"
            exposedHeaders:
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
            allowCredentials: true
      routes:
        - id: post-service-posts
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
          filters:
            - RewritePath=/api/posts/(?<path>.*), /api/posts/$\{path}

        - id: post-service-notifications
          uri: lb://post-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications/(?<path>.*), /api/notifications/$\{path}

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
          filters:
            - RewritePath=/api/comments/(?<path>.*), /api/comments/$\{path}

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**
          filters:
            - RewritePath=/api/reviews/(?<path>.*), /api/reviews/$\{path}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/