server:
  port: 8083

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: false
      routes:
        - id: post-service-posts
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
          filters:
            - RewritePath=/api/posts/(?<path>.*), /api/posts/$\{path}

        - id: post-service-notifications
          uri: lb://post-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - RewritePath=/api/notifications/(?<path>.*), /api/notifications/$\{path}

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comments/**
          filters:
            - RewritePath=/api/comments/(?<path>.*), /api/comments/$\{path}

        - id: review-service
          uri: lb://review-service
          predicates:
            - Path=/api/reviews/**
          filters:
            - RewritePath=/api/reviews/(?<path>.*), /api/reviews/$\{path}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
